package com.ansandy.moneysnap.shared.http;

public enum ApiErrorCode {
    INVALID_REQUEST,
    SESSION_REJECTED,
    MUTATION_CONFLICT,
    INTERNAL_ERROR,
    APPLE_REAUTHENTICATION_REJECTED,
    APPLE_REVOCATION_FAILED,
    APPLE_EVENT_REJECTED,
    APPLE_EVENT_UNSUPPORTED
}
