spring.application.name=moneysnap-api
server.address=127.0.0.1
spring.datasource.url=${NEON_RUNTIME_DATABASE_URL}
spring.datasource.username=${NEON_RUNTIME_DATABASE_USERNAME}
spring.datasource.password=${NEON_RUNTIME_DATABASE_PASSWORD}
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.url=${NEON_MIGRATION_DATABASE_URL}
spring.flyway.user=${NEON_MIGRATION_DATABASE_USERNAME}
spring.flyway.password=${NEON_MIGRATION_DATABASE_PASSWORD}

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never
management.endpoint.health.show-components=never
